blobStorageCredentials:
  s3:
    accessKeyId: admin
    secretAccessKey: password
gateway:
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
rbac:
  additionalNamespaces:
  - vvp-jobs
vvp:
  blobStorage:
    baseUri: s3://vvp
    s3:
      endpoint: http://minio.vvp.svc:9000
  globalDeploymentDefaults: |
    spec:
      state: RUNNING
      template:
        spec:
          resources:
            jobmanager:
              cpu: 0.5
              memory: 1G
            taskmanager:
              cpu: 0.5
              memory: 1G
          flinkConfiguration:
            state.backend: filesystem
            taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
            high-availability: vvp-kubernetes
            metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
            execution.checkpointing.interval: 10s
            execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
  persistence:
    type: local
  sqlService:
    pool:
      coreSize: 1
      maxSize: 1
