pyflink:
	echo -e $(pwd)
	cd ./pyflink/base
	echo -e $(pwd)
	docker build -t "ghcr.io/alex-y-kozlov-sandbox/pyflink/pyflink:1.14.3" .
	cd ../..
	echo -e $(pwd)
table-api:
	echo -e $(pwd)
	cd ./table-api
	echo -e $(pwd)
	docker build -t "ghcr.io/alex-y-kozlov-sandbox/pyflink/table-api:1.14.3" .
	cd ../..
	echo -e $(pwd)
